- app/controllers/earnings_and_benefits_controller.rb
- app/forms/earnings_and_benefits.rb
- app/views/earnings_and_benefits/edit.html.slim
- config/locales/en.yml
- spec/features/fill_in_earnings_and_benefits_page_spec.rb
- spec/forms/earnings_and_benefits_spec.rb
- test_common/capybara_selectors/embedded_single_choice_option.rb
- test_common/fixtures/personas.yml
- test_common/messaging/en.yml
- test_common/page_objects/earnings_and_benefits_page.rb
As before, this won't look 100% correct until the govuk form builder gem is updated
Otherwise please ensure the validation logic looks correct. The page should render much better than it did before, with the implementation of GDS hints.
> Validation of Earnings and Benefits page

- test_common/capybara/capybara_driver_helper.rb
One-line change to prevent the capybara port being forced
> Enable tests to run while dev server is running

- app/forms/your_representatives_details.rb
- app/validators/postcode_validator.rb
- spec/forms/your_representatives_details_spec.rb
As highlighted by @AlexaVB on RST-889, error messages now state that the field has been left blank.
> Show "blank" as the error when fields are left blank

- app/views/confirmation_of_supplied_details/edit.html.slim
- config/locales/en.yml
* Remove camel-casing on "Edit page" buttons.
* Fix typo ("we can provided you" -> "we can provide you")
* Re-introduce line explaining form submission
All the above as per comments left on RST-882
> RST-882 Fix strings on CoSD page

- app/views/claimants_details/edit.html.slim
- app/views/confirmation_of_supplied_details/edit.html.slim
- app/views/earnings_and_benefits/edit.html.slim
- app/views/employers_contract_claims/edit.html.slim
- app/views/respondents_details/edit.html.slim
- app/views/responses/edit.html.slim
- app/views/your_representatives/edit.html.slim
- app/views/your_representatives_details/edit.html.slim
This change places the error summary in a div that disables turbolinks, fixing a bug that causes the page to reload.
> RST-1045 Fix error summary links

- app/views/claimants_details/edit.html.slim
- config/locales/en.yml
Small change on `claimants_detail` page that changes the employment date hint text from "For example, 31 3 1980" to "For example, 31 **0**3 1980"
> RST-1155 Update hint string on employment dates

- lib/api_proxy.rb
Fixes bug that prevents ET3 contacting API to get an S3 presigned URL for the rtf upload.
> Fix API host URL

- app/views/additional_informations/edit.html.slim
- config/locales/en.yml
Upload additional info page did not inform user that the file should be RTF only. Updated existing strings and added some hint text to rectify this.
> RST-1259 Update strings to indicate file upload is RTF only

- app/assets/javascripts/uploadAdditionalInformation.js
- app/views/additional_informations/edit.html.slim
RST-1247 was a hotfix that removed the upload button from the submission data by removing it permanently from the page.
This change sees it temporarily removed, form submitted and added once again.
> RST-1258 Add upload button back after file is successfully uploaded

- app/views/additional_informations/edit.html.slim
- app/views/layouts/application.html.slim
**Force upload page to refresh on page load**
Before this change, uploading a file, progressing and then returning to the page would break the upload functionality. A new file could not be uploaded without reloading the page.
The page now informs Turbolinks that it needs to be loaded from fresh every time.
> RST-1238: Upload doesn't work when revisiting page

- app/controllers/confirmation_of_supplied_details_controller.rb
- app/views/confirmation_of_supplied_details/edit.html.slim
- app/views/layouts/application.html.slim
- config/routes.rb
Users could only overwrite the rtf file before, they could not delete it and submit nothing.
> RST-1273: Enable user to remove rtf file from ET3

- Dockerfile
- lib/tasks/non_digest_assets.rake
- public/404.html
This is a precursor to the ET3 mailer from ET API, can now use the assets at `<et3-url>/assets/govuk-template.css`, etc.
> RST-1278 Fix static assets

- app/forms/claimants_detail.rb
- app/forms/earnings_and_benefits.rb
- app/forms/employers_contract_claim.rb
- app/forms/respondents_detail.rb
- app/forms/response.rb
- app/forms/your_representatives_details.rb
- spec/forms/claimants_detail_spec.rb
- spec/forms/earnings_and_benefits_spec.rb
- spec/forms/employers_contract_claim_spec.rb
- spec/forms/respondents_detail_spec.rb
- spec/forms/response_spec.rb
- spec/forms/your_representatives_details_spec.rb
While picking up RST-1261 I noticed that there was a negative flow through the app that was very buggy.
When asking a user for their contact preference they are given a choice of email, post and fax. If they were to select email or fax they would be given the opportunity to enter an email address/fax number.
If they were to select email, enter an address, then change their minds and enter a fax number, the email address would still be submitted to the app.
RST-1261 alerted me to this as I wasn't validating properly so validation errors persisted if a different radio button was selected. However, despite validation being conditional, the submission was not conditional anywhere.
This PR corrects both the submission and validation of conditional data, resolving RST-1261 in the process.
> RST-1284 Fix conditional data being submitted unnecessarily

- config/locales/en.yml
- test_common/messaging/en.yml
As highlighted by Dan, the blank form download no longer works as the previous form was hosted on Jadu. 
This PR updates ET3 to use the file on GovUK assets publishing.
> Update PDF download link

- config/boot.rb
Current configuration is incorrect and will lead to production environments still searching for a `.env` file, this change removes the application dependency.
> Remove dotenv references from boot

- app/controllers/your_representatives_details_controller.rb
- app/forms/your_representatives_details.rb
- config/locales/en.yml
- test_common/fixtures/personas.yml
I forgot to remove references to the `representative_disability` attribute. It had no impact on the code but always best to keep the codebase tidy.
> Hotfix RST-1160: Remove Representative Disability References

- app/services/et_api_handler.rb
- spec/features/fill_in_whole_form_spec.rb
- test_common/helpers/setup.rb
This PR moves `disability` and `disability_information` into the `"BuildRespondent"` section of the submission hash, away from `"BuildRepresentative"`.
> RST-1360: Move Disability into BuildRespondent

- app/assets/javascripts/uploadAdditionalInformation.js
- app/helpers/uploaded_file_name_helper.rb
- app/views/confirmation_of_supplied_details/edit.html.slim
- config/locales/en.yml
- spec/features/fill_in_additional_information_page_spec.rb
- test_common/messaging/en.yml
On the 'Confirmation of Supplied Details' page there is a link to remove an uploaded file. This link should only render if a file has been uploaded. However, it currently renders any time the `:additional_information_answers` hash is populated with a key for `:upload_additional_information`, even though this is populated by default with an empty string.
This PR fixes that issue by checking if the string is empty. The logic is in a helper to keep the code clean and there is an accompanying spec.
> RST-1381: Fix remove file link

- app/assets/javascripts/disablePdfLink.js
- app/assets/javascripts/uploadAdditionalInformation.js
- app/controllers/static_pages_controller.rb
- app/helpers/uploaded_file_name_helper.rb
- app/views/confirmation_of_supplied_details/edit.html.slim
- config/locales/en.yml
- spec/features/access_form_submission_page_spec.rb
- spec/features/check_for_javascript_browser_errors_spec.rb
- spec/features/check_pdf_download_link_spec.rb
- spec/features/fill_in_additional_information_page_spec.rb
- spec/features/fill_in_whole_form_spec.rb
- test_common/capybara/capybara_driver_helper.rb
- test_common/helpers/pages.rb
- test_common/helpers/setup.rb
- test_common/messaging/en.yml
- test_common/page_objects/base_page.rb
- test_common/page_objects/form_submission_page.rb
- test_common/page_objects/start_page.rb
* Upon ET3 submission, if the generated PDF download is not ready yet, the link is disabled and the user is made aware that the file will be available shortly as opposed to getting a 404 error. (RST-1402: #100)
* Fix "Remove File" link to prevent it from showing when no file has been uploaded (RST-1381: #94)
* Fix JavaScript error caused by Dropzone being unable to find the uploader element. (RST-1397: #98)
* Prevent sessions being renewed when accessing the landing page after a period of over an hour away from the keyboard.
> Prepare v2.1.0

- app/assets/javascripts/disablePdfLink.js
* Upon ET3 submission, if the generated PDF download is not ready yet, the link is disabled and the user is made aware that the file will be available shortly as opposed to getting a 404 error. (RST-1402: #100 & Hotfix: #102)
* Fix "Remove File" link to prevent it from showing when no file has been uploaded (RST-1381: #94)
* Fix JavaScript error caused by Dropzone being unable to find the uploader element. (RST-1397: #98)
* Prevent sessions being renewed when accessing the landing page after a period of over an hour away from the keyboard.
> Prepare v2.1.1

- Gemfile
- config/boot.rb
This moves bootsnap into production environment only so as to avoid debugging issues until Ruby is patched.
> Only Use Bootsnap in Production

- config/locales/cy.yml
- config/locales/en.yml
- test_common/messaging/cy.yml
- test_common/messaging/en.yml
"Claimant's name" -> "Claimant's full name" and "Claimant's Details" -> "Claimant's details"
Welsh strings were confirmed by WLU via Dan
> RST-1530: Claimants Full Name and Titlecase Page Header

- config/environments/production.rb
Removes the asset prefix code - we dont need it
> RST-1758 ET3 (Azure) Asset configuration

- app/controllers/static_pages_controller.rb
- app/views/layouts/application.html.slim
- app/views/shared/_footer_links.html.slim
- app/views/static_pages/_policy_elements.html.slim
- app/views/static_pages/privacy.html.slim
- app/views/static_pages/terms.html.slim
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- spec/features/access_privacy_spec.rb
- spec/features/access_terms_spec.rb
- spec/features/view_footer_spec.rb
- spec/support/test_common.rb
- test_common/helpers/pages.rb
- test_common/messaging/cy.yml
- test_common/messaging/en.yml
- test_common/page_objects/base_page.rb
- test_common/page_objects/privacy_notice_page.rb
- test_common/page_objects/terms_and_conditions_page.rb
Merging back into the Terms & Conditions branch as I will release the entire footer/legal pages in one go.
After building the Privacy Notice I realised I had an opportunity to tidy up some rubbish code in the Terms branch. I have now removed the hashes from the `en` and `cy` yaml files and used arrays for bullet points instead.
> RST-1742: Add Privacy Notice to Footer

- app/controllers/static_pages_controller.rb
- app/views/shared/_footer_links.html.slim
- app/views/static_pages/cookies.html.slim
- app/views/static_pages/privacy.html.slim
- app/views/static_pages/terms.html.slim
- config/locales/cy.yml
- config/locales/en.yml
- config/routes.rb
- spec/features/access_cookies_spec.rb
- spec/features/view_footer_spec.rb
- test_common/helpers/pages.rb
- test_common/messaging/cy.yml
- test_common/messaging/en.yml
- test_common/page_objects/base_page.rb
- test_common/page_objects/cookies_page.rb
Adds a link to a legal cookies page in the footer with content as provided by Mia and approved by Dan
> RST-1754: Add Cookies Page to Footer

- app/views/confirmation_of_supplied_details/edit.html.slim
- config/locales/cy.yml
- config/locales/en.yml
- test_common/messaging/cy.yml
- test_common/messaging/en.yml
- test_common/page_objects/confirmation_of_supplied_details_page.rb
Updates strings and order of elements on the Confirmation of Supplied Details page.
Data was showing many users were dropping off on this page, presumably because they thought they had completed the journey. These changes aim to make it clearer that the journey has not been completed, thus decreasing exits on this page and increasing completions.
> RST-1778: Summary Page Revamp

- app/controllers/application_controller.rb
- app/controllers/form_submissions_controller.rb
- app/controllers/static_pages_controller.rb
- app/views/static_pages/index.html.slim
- config/routes.rb
- spec/features/clear_existing_session_with_new_session_spec.rb
If a user had partially filled in an ET3, left their computer and a new user began a "new session" within 60 minutes, the existing data would be shown.
This PR amends this behaviour so that clicking on the 'Start now' button always clears the session data.
> RST-1836: Clear Existing Response Data When Starting New Session

- app/views/layouts/application.html.slim
- app/views/shared/_footer_links.html.slim
- config/locales/cy.yml
- config/locales/en.yml
- spec/features/view_footer_spec.rb
- spec/features/view_sidebar_spec.rb
- test_common/messaging/cy.yml
- test_common/messaging/en.yml
In English this also renames the link from "How to contact us" to "Contact us" but I don't have Welsh strings so will do those as a separate ticket, later.
> RST-1755: Move 'Contact us' from Sidebar to Footer

- app/assets/stylesheets/global.css
- app/helpers/maintenance_notice_helper.rb
- app/views/layouts/application.html.slim
- app/views/shared/_maintenance_notice.html.slim
When `SHOW_DOWNTIME_BANNER` environment variable is present, this PR ensures that a maintenance banner is shown on all service pages.
```
[ ] Yes
[x] No
```
> RST-1884: Maintenance Notice when Env Var is Present

- config/environments/production.rb
This PR allows configuration of the raven client to allow SSL certificate verification to be disabled by setting RAVEN_SSL_VERIFICATION=false as an environment variable (defaults to true)
> SSL Certificate Verification Control 

- .travis.yml
When we switched from chromedriver-helper to webdrivers, travis seemed to be getting flaky. This was due to webdrivers having issues with downloading the drivers while in parallel. In v4 of the gem they added rake tasks to update the drivers before running the parallel specs, this PR adds them, which should fix the flaky travis builds.
```
[ ] Yes
[x] No
```
> RST-1950: Update .travis.yml to work with webdrivers gem in parallel

- config/routes.rb
Previously 500 error was shown when switching from Welsh to English on 'session expired' page. Add locale to path to enable the user to switch between languages.
```
[ ] Yes
[x] No
```
> RST-1922: Prevent 500 error when switching from cy to en when session expires

- app/views/static_pages/index.html.slim
- spec/features/view_sidebar_spec.rb
The link inside the sidebar menu for a blank pdf has been taken off all services pages.
```
[ ] Yes
[X ] No
```
> Took of the link for a blank pdf on all services pages.

- Gemfile
- Gemfile.lock
- config/database.yml
RST-2425
This PR fixes the database name in the test environment as having it reading from the environment variables did not make sense and caused issues when running locally in a full system environment
It also fixes an issue where file upload was not working
```
[ ] Yes
[ ] No
```
> Rst 2425 - Fixed test database name

- app/controllers/static_pages_controller.rb
- app/views/static_pages/index.html.slim
- spec/features/access_start_page_spec.rb
- spec/support/webmock.rb
Added a before action on the static pages. So when a user close a tab or go back to the start page it will be automatically signed out.
```
[ ] Yes
[X] No
```
> RST-3739 Users are now sign out on start page - Closed tab

- config/locales/cy.yml
- test_common/messaging/cy.yml
Added the welsh translation for the disability error message changes.
```
[ ] Yes
[X] No
```
> RST-4239 Welsh translation for content changes

- app/views/static_pages/index.html.slim
RST-4254
RST-4254 Fixed issue with h4s being in use instead of h2s on introduction page
```
[ ] Yes
[X] No
```
> RST-4254 Fixed issue with h4s being in use instead of h2s on introduction page

- app/validators/case_number_validator.rb
- docker/dev/docker-compose.yml
- spec/validators/case_number_validator_spec.rb
https://tools.hmcts.net/jira/browse/RST-4614
Allows '6' or '8' as the first digit of a case reference to allow for new ET1 cases from the reform system
```
[ ] Yes
[X] No
```
> RST-2614 Validation for et3 responses - allowing 6 or 8 as the first digit for reform ET1 cases

- Gemfile
- Gemfile.lock
- package.json
- yarn.lock
This cannot be merged until the et_gds_design_system gem has been released and the version number had its release candidate removed (i.e. it will be v5.2.1).  But, it can be reviewed ready and the version numbers will be bumped at last minute without further review.
```
[ ] Yes
[ ] No
```
> (RST-5296) Improve error handling in file uploads
