hmcts/et-pet-et3

app/controllers/responses_controller.rb
app/forms/response.rb
app/views/responses/edit.html.slim
config/locales/en.yml
spec/features/fill_in_response_page_spec.rb
spec/forms/response_spec.rb
test_common/fixtures/personas.yml
test_common/messaging/en.yml
test_common/page_objects/response_page.rb

Adds error handling to the Response Page.
Same disclaimer as the previous two PRs.

Validate Response Page

---

app/controllers/your_representatives_details_controller.rb
app/forms/your_representatives_details.rb
app/views/confirmation_of_supplied_details/edit.html.slim
app/views/your_representatives_details/edit.html.slim
config/locales/en.yml
spec/features/fill_in_whole_form_spec.rb
spec/features/fill_in_your_representatives_details_page_spec.rb
spec/forms/your_representatives_details_spec.rb
test_common/capybara_selectors/textarea_labelled.rb
test_common/fixtures/personas.yml
test_common/messaging/en.yml
test_common/page_objects/your_representatives_details_page.rb

As with previous pages, label doesn't show on radio button include validation.

Add Validation to Your Representative's Details Page

---

app/assets/stylesheets/confirmation_supplied_details.css
app/controllers/confirmation_of_supplied_details_controller.rb
app/forms/confirmation_of_supplied_details.rb
app/views/confirmation_of_supplied_details/edit.html.slim
config/locales/en.yml
spec/features/fill_in_confirmation_of_supplied_details_page_spec.rb
spec/features/fill_in_whole_form_spec.rb
spec/forms/confirmation_of_supplied_details_spec.rb
test_common/fixtures/personas.yml
test_common/helpers/setup.rb
test_common/messaging/en.yml
test_common/page_objects/confirmation_of_supplied_details_page.rb

Fixes everything in the ticket for RST-~8~962 and a bug that crashed the app if a question or page hadn't been answered

RST-962 Update Confirmation of Supplied Details page

---

app/controllers/form_submissions_controller.rb
app/services/et_api_handler.rb
app/views/claimants_details/edit.html.slim
app/views/respondents_details/edit.html.slim
spec/features/fill_in_whole_form_spec.rb
test_common/fixtures/personas.yml
test_common/helpers/setup.rb
test_common/messaging/en.yml
test_common/page_objects/claimants_details_page.rb

Writing the spec for the API took ages and I think will need your keen eye, @garytaylor. It works but I think it will need refactoring as there are functions and whatnot inside the expectations.
Everything should be functional but I'm prepared to refactor and see where that takes me.

Update request to match the latest version of the endpoint

---

app/assets/javascripts/uploadAdditionalInformation.js
app/views/additional_informations/edit.html.slim

This fixes the S3 form submission error. However, it does not return the button so further work is needed. Merge for now to push the fix into develop.

Feature/rst 1247 RTF Upload Bug

---

app/controllers/application_controller.rb
app/controllers/form_submissions_controller.rb
app/controllers/static_pages_controller.rb
app/views/static_pages/expired.html.slim
config/locales/en.yml
config/routes.rb

When a controller action is called a function to check the value of a session expiration is also called. If it passes, another function will add a 60 minute expiration key-value pair to the cookie.

Feature/RST-1028 Add session timeout

---

app/assets/stylesheets/global.css
app/views/layouts/application.html.slim
config/locales/en.yml
spec/features/view_sidebar_spec.rb
test_common/capybara_selectors/sidebar_titled.rb
test_common/messaging/en.yml
test_common/page_objects/base_page.rb

Add a sidebar with resources and guidance as per current prod.

Feature/RST-1106 Sidebar

---

.rspec
.travis.yml
Gemfile
Gemfile.lock
config/database.yml

Should reduce the amount of time travis takes

Add parallel testing configuration

---

app/controllers/disabilities_controller.rb
app/controllers/your_representatives_controller.rb
app/controllers/your_representatives_details_controller.rb
app/forms/disability.rb
app/forms/your_representatives_details.rb
app/services/et_api_handler.rb
app/views/confirmation_of_supplied_details/edit.html.slim
app/views/disabilities/edit.slim
app/views/your_representatives_details/edit.html.slim
config/locales/en.yml
config/routes.rb
spec/features/fill_in_disability_page_spec.rb
spec/features/fill_in_whole_form_spec.rb
spec/features/fill_in_your_representative_page_spec.rb
spec/features/fill_in_your_representatives_details_page_spec.rb
spec/features/view_sidebar_spec.rb
spec/forms/disability_spec.rb
spec/forms/your_representatives_details_spec.rb
test_common/fixtures/personas.yml
test_common/helpers/pages.rb
test_common/helpers/setup.rb
test_common/messaging/en.yml
test_common/page_objects/confirmation_of_supplied_details_page.rb
test_common/page_objects/disability_page.rb
test_common/page_objects/your_representatives_details_page.rb

Moves the disability question from the `your_representatives_details` page to a new page called `disability_question`.

RST-1160: Disability Questions

---

app/assets/javascripts/uploadAdditionalInformation.js
spec/features/check_for_javascript_browser_errors_spec.rb
test_common/helpers/pages.rb
test_common/page_objects/base_page.rb
test_common/page_objects/start_page.rb

Prevents JavaScript error on page which was caused by Dropzone not finding its binding element

RST-1397: Fix Dropzone Initiation Error

---

app/controllers/static_pages_controller.rb

Set expiry to 1m and tested locally, doesn't seem to have any adverse impact. Went green locally but I don't have a test explicitly for timeout (and think we agreed there isn't a test for it?).

RST-1402: Fix static_pages caching bug

---

.rubocop.yml
app/views/layouts/application.html.slim
app/views/shared/_google_tag_manager_body.html.erb
app/views/shared/_google_tag_manager_head.html.erb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
spec/requests/additional_information_page_spec.rb
spec/requests/claimants_details_page_spec.rb
spec/requests/confirmation_of_supplied_details_page_spec.rb
spec/requests/earnings_and_benefits_page_spec.rb
spec/requests/employers_contract_claim_page_spec.rb
spec/requests/respond_disability_page_spec.rb
spec/requests/respondents_details_page_spec.rb
spec/requests/response_page_spec.rb
spec/requests/your_representative_page_spec.rb
spec/requests/your_representatives_details_page_spec.rb
spec/support/shared_examples/google_tag_manager.rb
test_common/page_objects/base_page.rb

This PR adds google tag manager conditionally based on environment config

Add feature RST-1424-google-tag-manager

---

spec/features/fill_in_additional_information_page_spec.rb
spec/features/fill_in_whole_form_spec.rb
spec/support/setup_buckets.rb
test_common/helpers/s3_helpers.rb
test_common/helpers/setup.rb
test_common/page_objects/confirmation_of_supplied_details_page.rb

Uses the new minio server to test whether files are uploaded successfully

RST-1473: Upload Testing

---

config/locales/en.yml
test_common/messaging/en.yml

`Representative's name` -> `Representative's full name`

Request representative's full name

---

config/locales/en.yml
test_common/messaging/en.yml

`Name of contact (optional)` -> `Full name of contact (optional)`

Request Full Name of [Respondent] Contact

---

.travis.yml

Currently untested - should enable CC reporting automatically from Travis builds

Add Code Climate to Travis

---

app/views/layouts/application.html.slim

The issue is from Docker but it's easier to just add handling in ET3

Fix Welsh ENV Variable Handling

---

config/locales/cy.yml
test_common/messaging/cy.yml

RST-1645: Downcase Welsh for 'Number'

---

Gemfile
Gemfile.lock

Configured to use the azure_env_secrets gem ready for azure

RST-1752 ET3 (Azure) - Configure to use the azure_env_secrets gem

---

config/environments/production.rb

RST-1758 ET3 (Azure) Asset configuration
Doesnt need to be deployed specially - this is ready for azure

RST-1758 ET3 (Azure) Asset configuration

---

config/environments/production.rb

Log level is now controlled using RAILS_LOG_LEVEL in production

Log level is now controlled using RAILS_LOG_LEVEL in production

---

run.sh

This PR changes the run.sh script to be azure compatible and full system compatible

run.sh can now be run locally - i.e. full system

---

Dockerfile
azure-pipelines.yml

Commeting out ET3 onbuild 
```
[ ] Yes
[x] No
```

Adding Azure Pipelines Devops Functionality

---

app/helpers/maintenance_notice_helper.rb
config/locales/cy.yml
config/locales/en.yml

Use I18n via the `maintenance_notice` helper method to translate the month and the string in its entirety
```
[ ] Yes
[x] No
```

Add Welsh string add I18n compatibility

---

azure-pipelines.yml

Adding conditions to pipeline

---

Dockerfile
README.md
azure-pipelines.yml

ping.json fix and pipeline manual job support

---

Dockerfile
README.md
azure-pipelines.yml

ping.json fix and manual pipeline build job

---

azure-pipelines.yml

adding always condition to cleanup step

---

.travis.yml
azure-pipelines.yml

Addressing Travis error Can't find gem bundler

---

Gemfile
Gemfile.lock
app/controllers/additional_informations_controller.rb
spec/features/fill_in_additional_information_page_spec.rb

* Add spec for loading additional info page with a file uploaded
```
[ ] Yes
[x] No
```

RST-1890: Add test for recognising existing upload

---

azure-pipelines.yml
config/routes.rb

Update webdrivers before parallel tests run in Azure pipelines

---

app/views/static_pages/cookies.html.slim
app/views/static_pages/privacy.html.slim
config/locales/cy.yml
config/locales/en.yml
spec/features/access_cookies_spec.rb
spec/features/access_privacy_spec.rb
test_common/messaging/cy.yml
test_common/messaging/en.yml
test_common/page_objects/cookies_page.rb
test_common/page_objects/privacy_notice_page.rb

RST-2178 and RST-2185
Updatetd cookie and privacy policy
```
[ ] Yes
[X] No
```

Updatetd cookie and privacy policy

---

azure-pipelines.yml

removing blob storage assets
```
[ ] Yes
[x] No
```

removing blob storage assets

---

Gemfile
Gemfile.lock
app/assets/javascripts/disablePdfLink.js

v2.2.2
ES6 issues fixed
```
[ ] Yes
[ X] No
```

Changes made on et_dropzone_uploader Gem

---

config/locales/cy.yml
config/locales/en.yml
test_common/messaging/cy.yml
test_common/messaging/en.yml

Content changes for Your Representatives form
```
[ ] Yes
[ X] No
```

RST-1546 Changed content for Your Representative

---

app/controllers/feedbacks_controller.rb
app/forms/feedback.rb
app/services/et_api_handler.rb
app/views/feedbacks/new.html.slim
config/locales/cy.yml
config/locales/en.yml
config/routes.rb
spec/features/feedback_spec.rb
spec/support/factories/feedback_factory.rb
test_common/helpers/pages.rb
test_common/messaging/cy.yml
test_common/messaging/en.yml
test_common/page_objects/feedback_page.rb

Feedback feature added + tests

---

app/assets/stylesheets/flash-messages.scss
app/views/feedbacks/new.html.slim
app/views/shared/_flash_message.html.slim
app/views/static_pages/index.html.slim
config/locales/cy.yml
config/locales/en.yml
spec/features/feedback_spec.rb
test_common/capybara_selectors/flash_message_with_text.rb
test_common/messaging/cy.yml
test_common/messaging/en.yml
test_common/page_objects/feedback_page.rb

Feedback link added + flashes
```
[ ] Yes
[ X] No
```

RST-1918 Added feedback link and flashes.

---

Gemfile
Gemfile.lock
config/application.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb

RST-2144
This PR implements insights
```
[ ] Yes
[X] No
```

Rst 2144 insights

---

README.md
app/views/responses/edit.html.slim
config/locales/en.yml
test_common/messaging/en.yml

Following the GDS standard if you are asking just one question per page as recommended, you can set the contents of the <legend> as the page heading.
```
[ ] Yes
[X ] No
```

Rst 1544 response page

---

app/views/form_submissions/index.html.slim
config/locales/cy.yml
config/locales/en.yml

Added the content for the COVID19 on the form submission page.
```
[ ] Yes
[X ] No
```

RST-2550 COVID-19

---

config/locales/cy.yml
config/locales/en.yml

Content changes for the response page.
```
[ ] Yes
[ X] No
```

RST-1544 Changes made for content and translation.

---

app/views/form_submissions/index.html.slim
config/locales/cy.yml
config/locales/en.yml
spec/features/access_form_submission_page_spec.rb
test_common/messaging/cy.yml
test_common/messaging/en.yml

Added content and button link for feedback on the submission page.
```
[ ] Yes
[ X] No
```

Rst 2536 submission page

---

app/views/earnings_and_benefits/edit.html.slim
config/locales/cy.yml
config/locales/en.yml
test_common/messaging/cy.yml
test_common/messaging/en.yml

The content for the Earnings and Benefit page has been change for English and welsh.
```
[ ] Yes
[ X] No
```

RST-1542 Changed the content for the Earnings and benefit page

---

config/locales/cy.yml

Took off one line of content  from the Earnings and benefit page
```
[ ] Yes
[ X] No
```

RST-1542 Fixed content issue

---

config/locales/cy.yml

Revert "RST-1542 Fixed content issue"

---

Gemfile
Gemfile.lock
app/controllers/feedbacks_controller.rb
app/views/feedbacks/new.html.slim

CAPTCHA has been added to the feedback form.
```
[ ] Yes
[X ] No
```

RST-2533 Added CAPTCHA on feedback page

---

app/controllers/form_submissions_controller.rb
app/views/form_submissions/index.html.slim
config/locales/cy.yml
config/locales/en.yml
spec/features/access_form_submission_page_spec.rb

Fixed issue for the date translation
```
[ ] Yes
[ X] No
```

RST-2561 Fixed the Date translation

---

app/controllers/respondents_details_controller.rb
app/forms/respondents_detail.rb
app/services/et_api_handler.rb
app/views/confirmation_of_supplied_details/edit.html.slim
app/views/respondents_details/edit.html.slim
config/locales/cy.yml
config/locales/en.yml
spec/features/fill_in_respondents_details_page_spec.rb
spec/features/fill_in_whole_form_spec.rb
spec/forms/respondents_detail_spec.rb
spec/support/factories/respondent_factory.rb
test_common/helpers/setup.rb
test_common/messaging/cy.yml
test_common/messaging/en.yml
test_common/page_objects/confirmation_of_supplied_details_page.rb
test_common/page_objects/respondents_details_page.rb

Video call question field has been added + test
```
[ ] Yes
[ X] No
```

RST-2846 Added new video_call field + test

---

azure-pipelines.yml

Change pool for deploy and push tasks

---

app/forms/claimants_detail.rb
app/forms/respondents_detail.rb
config/locales/cy.yml
config/locales/en.yml
spec/features/fill_in_claimants_details_page_spec.rb
spec/forms/claimants_detail_spec.rb
spec/forms/respondents_detail_spec.rb
spec/support/factories/claimant_factory.rb
test_common/capybara_selectors/table_row_with_td_labelled.rb
test_common/helpers/setup.rb
test_common/messaging/cy.yml
test_common/messaging/en.yml
test_common/page_objects/claimants_details_page.rb

Took off some validation on the respondent page and the claimant details page + changed and added some tests
```
[ ] Yes
[ X] No
```

RST-3041 Took off some validations

---

azure-pipelines.yml

Fixed ruby version to 2.5

---

azure-pipelines.yml
spec/support/email_support/email_objects/new_reference_number_email_html.rb
spec/support/email_support/email_sent.rb

hotfix Sorted load order issue in tests

---

spec/features/access_cookies_spec.rb
spec/features/access_privacy_spec.rb
spec/features/fill_in_whole_form_spec.rb
spec/support/shared_examples/google_tag_manager.rb
test_common/messaging/cy.yml
test_common/messaging/en.yml
test_common/page_objects/base_page.rb

Commented out some test at the moment for the google_tag_manager and cookie_spec
```
[ ] Yes
[ X] No
```

Rst 3273 google_tag_manager

---

config/application.rb

HOTFIX - Corrected mail sender

---

app/views/confirmation_of_supplied_details/edit.html.slim
config/locales/cy.yml
config/locales/en.yml
spec/features/fill_in_claimants_details_page_spec.rb
spec/features/fill_in_disability_page_spec.rb
spec/features/fill_in_earnings_and_benefits_page_spec.rb
spec/features/fill_in_employers_contract_claim_page_spec.rb
spec/features/fill_in_respondents_details_page_spec.rb
spec/features/fill_in_response_page_spec.rb
spec/features/fill_in_your_representative_page_spec.rb
spec/features/fill_in_your_representatives_details_page_spec.rb
test_common/messaging/cy.yml
test_common/messaging/en.yml
test_common/page_objects/confirmation_of_supplied_details_page.rb

All button on the review page had been changed to pin point the page that the edit is for. 
Page object , and test had been changed too.
```
[ ] Yes
[ X] No
```

RST-2055 Changed edit button on review page

---

Dockerfile

Changes for the Docker Base image init process
```
[ ] Yes
[ X] No
```

Docker Base Image

---

Gemfile
Gemfile.lock

Changed the version number for et_dropzone_uploader.
```
[ ] Yes
[ X] No
```

RST-1493-RTFUpload

---

README.md
app/controllers/application_controller.rb
app/views/static_pages/maintenance.html.erb
config/application.rb

RST-4218 Maintenance Page

---

config/database.yml

Minor change to database config to quote value

---

app/controllers/status_controller.rb

Minor change to exclude maintenance page from status controller

---

config/locales/en.yml

Changed the Disability error message to be the same. For the error and the error summary
```
[ ] Yes
[X ] No
```

RST-4239 Changed Disability error message

---

config/routes.rb

RST-4482
```
[ ] Yes
[ ] No
```

RST-4482 Locale routes now have both english and welsh but defaults to english - fixes issue with email links

---

Dockerfile
Gemfile
Gemfile.lock
config/environments/development.rb
package.json
spec/features/access_cookies_spec.rb
spec/features/access_form_submission_page_spec.rb
spec/features/access_privacy_spec.rb
spec/features/access_terms_spec.rb
spec/features/check_for_javascript_browser_errors_spec.rb
spec/features/check_pdf_download_link_spec.rb
spec/features/fill_in_additional_information_page_spec.rb
spec/features/fill_in_confirmation_of_supplied_details_page_spec.rb
spec/features/fill_in_whole_form_spec.rb
spec/features/view_footer_spec.rb
spec/support/helpers/azure_helpers.rb
spec/support/helpers/setup.rb
yarn.lock

Rst 4686 New file upload system

---

Dockerfile.dev
config/environments/development.rb

RST-4439
```
[ ] Yes
[X] No
```

Changes for use with skaffold

---

.env.full_system.common
.env.full_system.development
.env.full_system.production
.gitignore
Dockerfile.development
Dockerfile.production
azure-pipelines.yml
bin/run_full_system

RST-5573
Modifications to assist docker compose based full system environment
```
[ ] Yes
[ ] No
```

Rst 5573 - Modifications to assist docker compose based full system environment

---

sonar-project.properties

(RST-5651) Correction to sonar project name

---

.gitignore
spec/rails_helper.rb

(RST-5651) Configured coverage

---

sonar-project.properties

(RST-5651) Fixed coverage again

---

Jenkinsfile_CNP
sonar-project.properties

(RST-5651) Coverage fixes

---

charts/et-pet-et3/Chart.yaml
charts/et-pet-et3/values.yaml

(RST-5651) Corrected API urls

---

charts/et-pet-et3/Chart.yaml
charts/et-pet-et3/values.yaml

(RST-5651) Fixed api urls

---

charts/et-pet-et3/Chart.yaml
charts/et-pet-et3/values.yaml

(RST-5651) Fixed sending host env var

---

app/controllers/cookies_controller.rb
config/application.rb
config/environments/production.rb
config/initializers/session_store.rb

(RST-5891) Secured cookies

---

.bundler-audit.yml

(RST-5895) Added bundler-audit config

---

.env.full_system.common

(RST-5918) Secure cookies disabled for et full system environment

---

.env.full_system.production

(RST-5920) Reduced logging level in full system environment

---

charts/et-pet-et3/Chart.yaml
charts/et-pet-et3/values.yaml

(RST-5976) Switch to using new app insights

---

Gemfile
Gemfile.lock

(RST-5642) GDS Gem upgraded to use ruby 3.2.2 in tests.

---

Gemfile
Gemfile.lock

(RST-5642) GDS Gem upgraded to use ruby 3.2.2 in tests. (#636)

---

Gemfile.lock

(RST-6287) Upgraded nokogiri (security issue)

---

.env.full_system.common
Gemfile.lock

(RST-6754) Fixed issue with smtp send error for et3 in full system env

---

Gemfile.lock

(RST-6810) Updated rexml

---

app/forms/claimants_detail.rb
app/types/et_date_type.rb
app/validators/date_validator.rb

Revert "RST-6254 - Allow EtDateType to handle 0/0/0 date and return valid error"

---

app/views/form_submissions/index.html.slim
config/locales/cy.yml
config/locales/en.yml
spec/support/capybara/capybara_driver_helper.rb
spec/support/messaging/cy.yml

This PR corrects the quick fix done where the english text was hard coded in

(RST-6875) Welsh content for submission page

---

Gemfile.lock
charts/et-pet-et3/Chart.yaml

https://tools.hmcts.net/jira/browse/RST-7191

RST-7191 - Helm update
